/* $Id$
 * $URL$
 *
 * Copyright (C) 2009 Scott Sibley <scott@starlon.net>
 *
 * This file is part of LCDControl.
 *
 * LCDControl is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LCDControl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LCDControl.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "Font_8x16.h"

int Font_8x16[10][16] = {
            {_OOOOO__,
             OOOOOOO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OOOOOOO_,
             _OOOOO__,
             ________},
            {_OO_____,
             OOO_____,
             OOO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             _OO_____,
             OOOO____,
             OOOO____,
             ________},
            {_OOOOO__,
             OOOOOOO_,
             OO___OO_,
             _____OO_,
             _____OO_,
             _____OO_,
             ___OOOO_,
             _OOOOO__,
             OOO_____,
             OO______,
             OO______,
             OO______,
             OO______,
             OOOOOOO_,
             OOOOOOO_,
             ________},
            {_OOOOO__,
             OOOOOOO_,
             OO___OO_,
             _____OO_,
             _____OO_,
             ____OOO_,
             ___OOO__,
             __OOO___,
             ___OOO__,
             ____OOO_,
             _____OO_,
             _____OO_,
             OO___OO_,
             OOOOOOO_,
             _OOOOO__,
             ________},
            {OO__OO__,
             OO__OO__,
             OO__OO__,
             OO__OO__,
             OO__OO__,
             OO__OO__,
             OO__OO__,
             OOOOOOO_,
             OOOOOOO_,
             ____OO__,
             ____OO__,
             ____OO__,
             ____OO__,
             ____OO__,
             ____OO__,
             ________},
            {OOOOOOO_,
             OOOOOOO_,
             OO______,
             OO______,
             OO______,
             OO______,
             OOOOOO__,
             _OOOOO__,
             _____OO_,
             _____OO_,
             _____OO_,
             _____OO_,
             _____OO_,
             OOOOOO__,
             OOOOO___,
             ________},
            {____OO__,
             ___OO___,
             __OO____,
             _OO_____,
             OO______,
             OO______,
             OOOOO___,
             OOOOOO__,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OOOOOOO_,
             _OOOOO__,
             __OOO___,
             ________},
            {OOOOOOO_,
             OOOOOOO_,
             _____OO_,
             _____OO_,
             _____OO_,
             _____OO_,
             ____OO__,
             ___OO___,
             __OO____,
             __OO____,
             __OO____,
             __OO____,
             __OO____,
             __OO____,
             __OO____,
             ________},
            {_OOOOO__,
             OOOOOOO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             _OOOOO__,
             __OOO___,
             _OOOOO__,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OOOOOOO_,
             _OOOOO__,
             ________},
            {__OOO___,
             _OOOOO__,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OO___OO_,
             OOOOOOO_,
             _OOOOOO_,
             _____OO_,
             _____OO_,
             ____OO__,
             ___OOO__,
             OOOOO___,
             OOO_____,
             ________},
};
