/* $Id$
 * $URL$
 *
 * Copyright (C) 2009 Scott Sibley <scott@starlon.net>
 *
 * This file is part of LCDControl.
 *
 * LCDControl is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LCDControl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LCDControl.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __FONT_8X16_H__
#define __FONT_8X16_H__

#define ________ 0x0
#define _______O 0x1
#define ______O_ 0x2
#define ______OO 0x3
#define _____O__ 0x4
#define _____O_O 0x5
#define _____OO_ 0x6
#define _____OOO 0x7
#define ____O___ 0x8
#define ____O__O 0x9
#define ____O_O_ 0xa
#define ____O_OO 0xb
#define ____OO__ 0xc
#define ____OO_O 0xd
#define ____OOO_ 0xe
#define ____OOOO 0xf
#define ___O____ 0x10
#define ___O___O 0x11
#define ___O__O_ 0x12
#define ___O__OO 0x13
#define ___O_O__ 0x14
#define ___O_O_O 0x15
#define ___O_OO_ 0x16
#define ___O_OOO 0x17
#define ___OO___ 0x18
#define ___OO__O 0x19
#define ___OO_O_ 0x1a
#define ___OO_OO 0x1b
#define ___OOO__ 0x1c
#define ___OOO_O 0x1d
#define ___OOOO_ 0x1e
#define ___OOOOO 0x1f
#define __O_____ 0x20
#define __O____O 0x21
#define __O___O_ 0x22
#define __O___OO 0x23
#define __O__O__ 0x24
#define __O__O_O 0x25
#define __O__OO_ 0x26
#define __O__OOO 0x27
#define __O_O___ 0x28
#define __O_O__O 0x29
#define __O_O_O_ 0x2a
#define __O_O_OO 0x2b
#define __O_OO__ 0x2c
#define __O_OO_O 0x2d
#define __O_OOO_ 0x2e
#define __O_OOOO 0x2f
#define __OO____ 0x30
#define __OO___O 0x31
#define __OO__O_ 0x32
#define __OO__OO 0x33
#define __OO_O__ 0x34
#define __OO_O_O 0x35
#define __OO_OO_ 0x36
#define __OO_OOO 0x37
#define __OOO___ 0x38
#define __OOO__O 0x39
#define __OOO_O_ 0x3a
#define __OOO_OO 0x3b
#define __OOOO__ 0x3c
#define __OOOO_O 0x3d
#define __OOOOO_ 0x3e
#define __OOOOOO 0x3f
#define _O______ 0x40
#define _O_____O 0x41
#define _O____O_ 0x42
#define _O____OO 0x43
#define _O___O__ 0x44
#define _O___O_O 0x45
#define _O___OO_ 0x46
#define _O___OOO 0x47
#define _O__O___ 0x48
#define _O__O__O 0x49
#define _O__O_O_ 0x4a
#define _O__O_OO 0x4b
#define _O__OO__ 0x4c
#define _O__OO_O 0x4d
#define _O__OOO_ 0x4e
#define _O__OOOO 0x4f
#define _O_O____ 0x50
#define _O_O___O 0x51
#define _O_O__O_ 0x52
#define _O_O__OO 0x53
#define _O_O_O__ 0x54
#define _O_O_O_O 0x55
#define _O_O_OO_ 0x56
#define _O_O_OOO 0x57
#define _O_OO___ 0x58
#define _O_OO__O 0x59
#define _O_OO_O_ 0x5a
#define _O_OO_OO 0x5b
#define _O_OOO__ 0x5c
#define _O_OOO_O 0x5d
#define _O_OOOO_ 0x5e
#define _O_OOOOO 0x5f
#define _OO_____ 0x60
#define _OO____O 0x61
#define _OO___O_ 0x62
#define _OO___OO 0x63
#define _OO__O__ 0x64
#define _OO__O_O 0x65
#define _OO__OO_ 0x66
#define _OO__OOO 0x67
#define _OO_O___ 0x68
#define _OO_O__O 0x69
#define _OO_O_O_ 0x6a
#define _OO_O_OO 0x6b
#define _OO_OO__ 0x6c
#define _OO_OO_O 0x6d
#define _OO_OOO_ 0x6e
#define _OO_OOOO 0x6f
#define _OOO____ 0x70
#define _OOO___O 0x71
#define _OOO__O_ 0x72
#define _OOO__OO 0x73
#define _OOO_O__ 0x74
#define _OOO_O_O 0x75
#define _OOO_OO_ 0x76
#define _OOO_OOO 0x77
#define _OOOO___ 0x78
#define _OOOO__O 0x79
#define _OOOO_O_ 0x7a
#define _OOOO_OO 0x7b
#define _OOOOO__ 0x7c
#define _OOOOO_O 0x7d
#define _OOOOOO_ 0x7e
#define _OOOOOOO 0x7f
#define O_______ 0x80
#define O______O 0x81
#define O_____O_ 0x82
#define O_____OO 0x83
#define O____O__ 0x84
#define O____O_O 0x85
#define O____OO_ 0x86
#define O____OOO 0x87
#define O___O___ 0x88
#define O___O__O 0x89
#define O___O_O_ 0x8a
#define O___O_OO 0x8b
#define O___OO__ 0x8c
#define O___OO_O 0x8d
#define O___OOO_ 0x8e
#define O___OOOO 0x8f
#define O__O____ 0x90
#define O__O___O 0x91
#define O__O__O_ 0x92
#define O__O__OO 0x93
#define O__O_O__ 0x94
#define O__O_O_O 0x95
#define O__O_OO_ 0x96
#define O__O_OOO 0x97
#define O__OO___ 0x98
#define O__OO__O 0x99
#define O__OO_O_ 0x9a
#define O__OO_OO 0x9b
#define O__OOO__ 0x9c
#define O__OOO_O 0x9d
#define O__OOOO_ 0x9e
#define O__OOOOO 0x9f
#define O_O_____ 0xa0
#define O_O____O 0xa1
#define O_O___O_ 0xa2
#define O_O___OO 0xa3
#define O_O__O__ 0xa4
#define O_O__O_O 0xa5
#define O_O__OO_ 0xa6
#define O_O__OOO 0xa7
#define O_O_O___ 0xa8
#define O_O_O__O 0xa9
#define O_O_O_O_ 0xaa
#define O_O_O_OO 0xab
#define O_O_OO__ 0xac
#define O_O_OO_O 0xad
#define O_O_OOO_ 0xae
#define O_O_OOOO 0xaf
#define O_OO____ 0xb0
#define O_OO___O 0xb1
#define O_OO__O_ 0xb2
#define O_OO__OO 0xb3
#define O_OO_O__ 0xb4
#define O_OO_O_O 0xb5
#define O_OO_OO_ 0xb6
#define O_OO_OOO 0xb7
#define O_OOO___ 0xb8
#define O_OOO__O 0xb9
#define O_OOO_O_ 0xba
#define O_OOO_OO 0xbb
#define O_OOOO__ 0xbc
#define O_OOOO_O 0xbd
#define O_OOOOO_ 0xbe
#define O_OOOOOO 0xbf
#define OO______ 0xc0
#define OO_____O 0xc1
#define OO____O_ 0xc2
#define OO____OO 0xc3
#define OO___O__ 0xc4
#define OO___O_O 0xc5
#define OO___OO_ 0xc6
#define OO___OOO 0xc7
#define OO__O___ 0xc8
#define OO__O__O 0xc9
#define OO__O_O_ 0xca
#define OO__O_OO 0xcb
#define OO__OO__ 0xcc
#define OO__OO_O 0xcd
#define OO__OOO_ 0xce
#define OO__OOOO 0xcf
#define OO_O____ 0xd0
#define OO_O___O 0xd1
#define OO_O__O_ 0xd2
#define OO_O__OO 0xd3
#define OO_O_O__ 0xd4
#define OO_O_O_O 0xd5
#define OO_O_OO_ 0xd6
#define OO_O_OOO 0xd7
#define OO_OO___ 0xd8
#define OO_OO__O 0xd9
#define OO_OO_O_ 0xda
#define OO_OO_OO 0xdb
#define OO_OOO__ 0xdc
#define OO_OOO_O 0xdd
#define OO_OOOO_ 0xde
#define OO_OOOOO 0xdf
#define OOO_____ 0xe0
#define OOO____O 0xe1
#define OOO___O_ 0xe2
#define OOO___OO 0xe3
#define OOO__O__ 0xe4
#define OOO__O_O 0xe5
#define OOO__OO_ 0xe6
#define OOO__OOO 0xe7
#define OOO_O___ 0xe8
#define OOO_O__O 0xe9
#define OOO_O_O_ 0xea
#define OOO_O_OO 0xeb
#define OOO_OO__ 0xec
#define OOO_OO_O 0xed
#define OOO_OOO_ 0xee
#define OOO_OOOO 0xef
#define OOOO____ 0xf0
#define OOOO___O 0xf1
#define OOOO__O_ 0xf2
#define OOOO__OO 0xf3
#define OOOO_O__ 0xf4
#define OOOO_O_O 0xf5
#define OOOO_OO_ 0xf6
#define OOOO_OOO 0xf7
#define OOOOO___ 0xf8
#define OOOOO__O 0xf9
#define OOOOO_O_ 0xfa
#define OOOOO_OO 0xfb
#define OOOOOO__ 0xfc
#define OOOOOO_O 0xfd
#define OOOOOOO_ 0xfe
#define OOOOOOOO 0xff

#endif
