#include <string>

std::string lcdcontrol_config = ""
"{\n"
"    \"variables\": {\n"
"        \"foo\": 220\n"
"    },\n"
"    \"display_video\": {\n"
"        \"driver\": \"video\",\n"
"        \"layers\": 4,\n"
"        \"foreground\": \"FFFFFFFF\",\n"
"        \"background\": \"00000000\",\n"
"        \"fill\": 1,\n"
"        \"cols\": 256,\n"
"        \"rows\": 64,\n"
"        \"layout-timeout\": 0,\n"
"        \"update\": 100,\n"
"        //\"widget0\": \"widget_key_up\",\n"
"        //\"widget1\": \"widget_key_down\",\n"
"        //\"widget2\": \"widget_netstat_script\",\n"
"        \"transition-speed\": 100,\n"
"        \"refresh-rate\": 5,\n"
"        \"layout0\": \"layout_full\"\n"
"    },\n"
"    \"layout_full\": {\n"
"        \"layer4\": {\n"
"            \"row1\": {\n"
"                \"col1\": \"widget_infinite_256x64\"\n"
"            }\n"
"        },\n"
"        \"layer3\": {\n"
"            \"row1\": {\n"
"                \"col1\": \"widget_libvisual_256x64\"\n"
"            }\n"
"        },\n"
"        \"layer2\": {\n"
"            \"row1\": {\n"
"                \"col1\": \"widget_histogram_large\"\n"
"            }\n"
"        },\n"
"        \"layer1\": {\n"
"            \"row2\": {\n"
"                \"col1\": \"widget_icon_heart\",\n"
"                \"col2\": \"widget_icon_heartbeat\",\n"
"                \"col3\": \"widget_icon_heart\",\n"
"                \"col4\": \"widget_icon_heartbeat\",\n"
"                \"col5\": \"widget_icon_heart\",\n"
"                \"col6\": \"widget_icon_heartbeat\",\n"
"                \"col7\": \"widget_icon_heart\",\n"
"                \"col8\": \"widget_icon_heartbeat\",\n"
"                \"col9\": \"widget_icon_heart\",\n"
"                \"col10\": \"widget_icon_heartbeat\",\n"
"                \"col11\": \"widget_icon_heart\",\n"
"                \"col12\": \"widget_icon_heartbeat\",\n"
"                \"col13\": \"widget_icon_heart\",\n"
"                \"col14\": \"widget_icon_heartbeat\",\n"
"                \"col15\": \"widget_icon_heart\",\n"
"                \"col16\": \"widget_icon_heartbeat\",\n"
"                \"col17\": \"widget_icon_heart\",\n"
"                \"col18\": \"widget_icon_heartbeat\",\n"
"                \"col19\": \"widget_icon_heart\",\n"
"                \"col20\": \"widget_icon_heartbeat\"\n"
"            },\n"
"            \"row3\": {\n"
"                \"col4\": \"widget_cpu_label\",\n"
"                \"col8\": \"widget_bignums\",\n"
"                \"col11\": \"widget_percent\"\n"
"            },\n"
"            \"row5\": {\n"
"                \"col1\": \"widget_FSSpace\"\n"
"            },\n"
"            \"transition\": \"U\"\n"
"        }\n"
"    },\n"
"    \"layout_2x16\": {\n"
"        \"row1\": {\n"
"                \"col1\": \"widget_CPULabel\",\n"
"                \"col5\": \"widget_CPU\"\n"
"        },\n"
"        \"row2\": {\n"
"                \"col1\": \"widget_page_label\",\n"
"                \"col11\": \"widget_page\"\n"
"        }\n"
"    },\n"
"    \"layout_histogram_large\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_histogram_large\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    },\n"
"    \"layout_full_256x64\": {\n"
"        \"layer2\": {\n"
"            \"row1\": {\n"
"                \"col1\": \"widget_histogram_large\"\n"
"            }\n"
"        },\n"
"        \"layer3\": {\n"
"            \"row1\": {\n"
"                \"col1\": \"widget_libvisual\"\n"
"            }\n"
"        },\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_CPULabel\",\n"
"            \"col6\": \"widget_CPU\",\n"
"            \"col11\": \"widget_CPUBar\",\n"
"            \"col21\": \"widget_RAMLabel\",\n"
"            \"col26\": \"widget_RAMFree\",\n"
"            \"col31\": \"widget_RAMTotal\"\n"
"        },\n"
"        \"row2\": {\n"
"            \"col1\": \"widget_IDELabel\",\n"
"            \"col6\": \"widget_IDEIn\",\n"
"            \"col17\": \"widget_IDEOut\",\n"
"            \"col28\": \"widget_IDEBar\"\n"
"        },\n"
"        \"row3\": {\n"
"            \"col1\": \"widget_FSSpace\"\n"
"        },\n"
"        \"row4\": {\n"
"            \"col1\": \"widget_WLANLabel\",\n"
"            \"col6\": \"widget_WLANIn\",\n"
"            \"col17\": \"widget_WLANOut\",\n"
"            \"col28\": \"widget_WLANBar\"\n"
"        },\n"
"        \"row6\": {\n"
"            \"col1\": \"widget_icon_heartbeat\",\n"
"            \"col2\": \"widget_icon_ekg\",\n"
"            \"col3\": \"widget_icon_heart\",\n"
"            \"col4\": \"widget_icon_blob\",\n"
"            \"col5\": \"widget_icon_wave\",\n"
"            \"col6\": \"widget_icon_timer\",\n"
"            \"col7\": \"widget_icon_rain\",\n"
"            \"col8\": \"widget_icon_karo\",\n"
"            \"col9\": \"widget_icon_heartbeat\",\n"
"            \"col10\": \"widget_icon_ekg\",\n"
"            \"col11\": \"widget_icon_heart\",\n"
"            \"col12\": \"widget_icon_blob\",\n"
"            \"col13\": \"widget_icon_wave\",\n"
"            \"col14\": \"widget_icon_timer\",\n"
"            \"col15\": \"widget_icon_rain\",\n"
"            \"col16\": \"widget_icon_karo\",\n"
"            \"col17\": \"widget_icon_heartbeat\",\n"
"            \"col18\": \"widget_icon_ekg\",\n"
"            \"col19\": \"widget_icon_heart\",\n"
"            \"col20\": \"widget_icon_blob\",\n"
"            \"col21\": \"widget_icon_wave\",\n"
"            \"col22\": \"widget_icon_timer\",\n"
"            \"col23\": \"widget_icon_rain\",\n"
"            \"col24\": \"widget_icon_karo\",\n"
"            \"col25\": \"widget_icon_heartbeat\",\n"
"            \"col26\": \"widget_icon_ekg\",\n"
"            \"col27\": \"widget_icon_heart\",\n"
"            \"col28\": \"widget_icon_blob\",\n"
"            \"col29\": \"widget_icon_wave\",\n"
"            \"col30\": \"widget_icon_timer\",\n"
"            \"col31\": \"widget_icon_rain\",\n"
"            \"col32\": \"widget_icon_karo\",\n"
"            \"col33\": \"widget_icon_heartbeat\",\n"
"            \"col34\": \"widget_icon_ekg\",\n"
"            \"col35\": \"widget_icon_heart\",\n"
"            \"col36\": \"widget_icon_blob\",\n"
"            \"col37\": \"widget_icon_blob\",\n"
"            \"col38\": \"widget_icon_wave\",\n"
"            \"col39\": \"widget_icon_timer\",\n"
"            \"col40\": \"widget_icon_rain\",\n"
"            \"col41\": \"widget_icon_karo\",\n"
"            \"col42\": \"widget_icon_heartbeat\"\n"
"            \n"
"        },\n"
"        \"row7\": {\n"
"            \"col1\": \"widget_Time\",\n"
"            \"col22\": \"widget_UptimeLabel\",\n"
"            \"col30\": \"widget_Uptime\"\n"
"        },\n"
"        \"row8\": {\n"
"            \"col1\": \"widget_bottom_ticker\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    },\n"
"    \"layout_blank\": {\n"
"        \"layout-timeout\": 0\n"
"    },\n"
"    \"layout_pcm_256x64\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_pcm_256x64\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    },\n"
"    \"layout_pcm_24x16\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_pcm_24x16\"\n"
"        }\n"
"    },\n"
"    \"layout_peak\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_peak\"\n"
"        }\n"
"    },\n"
"    \"layout_spectrum\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_spectrum\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    },\n"
"    \"layout_1\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_cpu_label\",\n"
"            //\"col11\": \"widget_cpu_histogram\",\n"
"            \"col6\": \"widget_cpu\"\n"
"        }, \n"
"        \"row2\": {\n"
"            //\"col1\": \"widget_wlan0_label\", \n"
"            //\"col11\": \"widget_wlan0_histogram\",\n"
"            //\"col7\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"           //\"col1\": \"widget_ram_label\",\n"
"           //\"col5\": \"widget_ram_active\",\n"
"           //\"col11\": \"widget_ram_total\"\n"
"        }, \n"
"        \"row4\": {\n"
"            //\"col1\": \"widget_bottom_ticker\"\n"
"        }, \n"
"        \"transition\": \"B\"\n"
"    }, \n"
"    \"layout_visualization\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_pcm_24x16\"\n"
"            //\"col17\": \"widget_pcm_24x16\",\n"
"            //\"col9\": \"widget_pcm_24x16\"\n"
"        },\n"
"        \"row3\": {\n"
"            //\"col13\": \"widget_pcm_24x16\",\n"
"            //\"col5\": \"widget_pcm_24x16\"\n"
"        },\n"
"        \"transition\": \"B\"\n"
"    },\n"
"    \"layout_american_flag\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_american_flag\",\n"
"            \"col17\": \"widget_gif_american_flag\", \n"
"            \"col9\": \"widget_gif_american_flag\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col13\": \"widget_gif_american_flag\", \n"
"            \"col5\": \"widget_gif_american_flag\"\n"
"        },\n"
"        \"transition\": \"D\"\n"
"    }, \n"
"    \"layout_bar\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_ram_label\",\n"
"            \"col10\": \"widget_ram_total\", \n"
"            \"col5\": \"widget_ram_active\"\n"
"        },\n"
"        \"row2\": {\n"
"            \"col1\": \"widget_wlan0_label\",\n"
"            \"col10\": \"widget_wlan0_bar\",\n"
"            \"col7\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_icon_wave\",\n"
"            \"col10\": \"widget_icon_ekg\", \n"
"            \"col11\": \"widget_icon_rain\", \n"
"            \"col12\": \"widget_icon_blob\", \n"
"            \"col13\": \"widget_icon_wave\", \n"
"            \"col14\": \"widget_icon_ekg\", \n"
"            \"col15\": \"widget_icon_rain\", \n"
"            \"col16\": \"widget_icon_blob\", \n"
"            \"col17\": \"widget_icon_wave\", \n"
"            \"col18\": \"widget_icon_ekg\", \n"
"            \"col19\": \"widget_icon_rain\",\n"
"            \"col2\": \"widget_icon_ekg\", \n"
"            \"col20\": \"widget_icon_blob\", \n"
"            \"col3\": \"widget_icon_rain\", \n"
"            \"col4\": \"widget_icon_blob\", \n"
"            \"col5\": \"widget_icon_wave\", \n"
"            \"col6\": \"widget_icon_ekg\", \n"
"            \"col7\": \"widget_icon_rain\", \n"
"            \"col8\": \"widget_icon_blob\", \n"
"            \"col9\": \"widget_icon_wave\"\n"
"        },\n"
"        \"row4\": {\n"
"            \"col1\": \"widget_bottom_ticker\"\n"
"        }, \n"
"        \"transition\": \"U\"\n"
"    }, \n"
"    \"layout_bignums\": {\n"
"        \"row2\": {\n"
"            \"col1\": \"widget_cpu_label\", \n"
"            \"col10\": \"widget_bignums\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col14\": \"widget_percent\"\n"
"        },\n"
"        \"transition\": \"D\"\n"
"    }, \n"
"    \"layout_banner\": {\n"
"        \"row1\": {\n"
"                \"col2\": \"widget_vis_banner\",\n"
"                \"col12\": \"widget_vis_banner\"\n"
"        },\n"
"        \"row2\": {\n"
"                \"col2\": \"widget_vis_banner\",\n"
"                \"col12\": \"widget_vis_banner\"\n"
"        },\n"
"        \"row3\": {\n"
"            \"col1\": \"widget_Time\"\n"
"\n"
"        },\n"
"        \"row4\": {\n"
"                \"col2\": \"widget_vis_banner\",\n"
"                \"col12\": \"widget_vis_banner\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    },\n"
"    \"layout_bolt\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_bolt\", \n"
"            \"col17\": \"widget_gif_bolt\", \n"
"            \"col9\": \"widget_gif_bolt\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col13\": \"widget_gif_bolt\", \n"
"            \"col5\": \"widget_gif_bolt\"\n"
"        },\n"
"        \"transition\": \"B\"\n"
"    }, \n"
"    \"layout_dolby\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_dolby\", \n"
"            \"col17\": \"widget_gif_dolby\", \n"
"            \"col9\": \"widget_gif_dolby\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col13\": \"widget_gif_dolby\", \n"
"            \"col5\": \"widget_gif_dolby\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    }, \n"
"    \"layout_icons\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_icon_heartbeat\", \n"
"            \"col10\": \"widget_icon_ekg\", \n"
"            \"col11\": \"widget_icon_heart\", \n"
"            \"col12\": \"widget_icon_blob\", \n"
"            \"col13\": \"widget_icon_wave\", \n"
"            \"col14\": \"widget_icon_timer\", \n"
"            \"col15\": \"widget_icon_rain\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_heartbeat\", \n"
"            \"col18\": \"widget_icon_ekg\", \n"
"            \"col19\": \"widget_icon_heart\", \n"
"            \"col2\": \"widget_icon_ekg\", \n"
"            \"col20\": \"widget_icon_blob\", \n"
"            \"col3\": \"widget_icon_heart\", \n"
"            \"col4\": \"widget_icon_blob\", \n"
"            \"col5\": \"widget_icon_wave\", \n"
"            \"col6\": \"widget_icon_timer\", \n"
"            \"col7\": \"widget_icon_rain\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_heartbeat\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_icon_wave\", \n"
"            \"col10\": \"widget_icon_timer\", \n"
"            \"col11\": \"widget_icon_rain\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_heartbeat\", \n"
"            \"col14\": \"widget_icon_ekg\", \n"
"            \"col15\": \"widget_icon_heart\", \n"
"            \"col16\": \"widget_icon_blob\", \n"
"            \"col17\": \"widget_icon_wave\", \n"
"            \"col18\": \"widget_icon_timer\", \n"
"            \"col19\": \"widget_icon_rain\", \n"
"            \"col2\": \"widget_icon_timer\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_rain\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_heartbeat\", \n"
"            \"col6\": \"widget_icon_ekg\", \n"
"            \"col7\": \"widget_icon_heart\", \n"
"            \"col8\": \"widget_icon_blob\", \n"
"            \"col9\": \"widget_icon_wave\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_icon_heartbeat\", \n"
"            \"col10\": \"widget_icon_ekg\", \n"
"            \"col11\": \"widget_icon_heart\", \n"
"            \"col12\": \"widget_icon_blob\", \n"
"            \"col13\": \"widget_icon_wave\", \n"
"            \"col14\": \"widget_icon_timer\", \n"
"            \"col15\": \"widget_icon_rain\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_heartbeat\", \n"
"            \"col18\": \"widget_icon_ekg\", \n"
"            \"col19\": \"widget_icon_heart\", \n"
"            \"col2\": \"widget_icon_ekg\", \n"
"            \"col20\": \"widget_icon_blob\", \n"
"            \"col3\": \"widget_icon_heart\", \n"
"            \"col4\": \"widget_icon_blob\", \n"
"            \"col5\": \"widget_icon_wave\", \n"
"            \"col6\": \"widget_icon_timer\", \n"
"            \"col7\": \"widget_icon_rain\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_heartbeat\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_icon_wave\", \n"
"            \"col10\": \"widget_icon_timer\", \n"
"            \"col11\": \"widget_icon_rain\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_heartbeat\", \n"
"            \"col14\": \"widget_icon_ekg\", \n"
"            \"col15\": \"widget_icon_heart\", \n"
"            \"col16\": \"widget_icon_blob\", \n"
"            \"col17\": \"widget_icon_wave\", \n"
"            \"col18\": \"widget_icon_timer\", \n"
"            \"col19\": \"widget_icon_rain\", \n"
"            \"col2\": \"widget_icon_timer\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_rain\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_heartbeat\", \n"
"            \"col6\": \"widget_icon_ekg\", \n"
"            \"col7\": \"widget_icon_heart\", \n"
"            \"col8\": \"widget_icon_blob\", \n"
"            \"col9\": \"widget_icon_wave\"\n"
"        }, \n"
"        \"transition\": \"B\"\n"
"    }, \n"
"    \"layout_intel\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_intel\", \n"
"            \"col17\": \"widget_gif_intel\", \n"
"            \"col9\": \"widget_gif_intel\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col13\": \"widget_gif_intel\", \n"
"            \"col5\": \"widget_gif_intel\"\n"
"        },\n"
"        \"transition\": \"R\"\n"
"    }, \n"
"    \"layout_karo\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_icon_karo\", \n"
"            \"col10\": \"widget_icon_karo\", \n"
"            \"col11\": \"widget_icon_karo\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_karo\", \n"
"            \"col14\": \"widget_icon_karo\", \n"
"            \"col15\": \"widget_icon_karo\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_karo\", \n"
"            \"col18\": \"widget_icon_karo\", \n"
"            \"col19\": \"widget_icon_karo\", \n"
"            \"col2\": \"widget_icon_karo\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_karo\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_karo\", \n"
"            \"col6\": \"widget_icon_karo\", \n"
"            \"col7\": \"widget_icon_karo\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_karo\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_icon_karo\", \n"
"            \"col10\": \"widget_icon_karo\", \n"
"            \"col11\": \"widget_icon_karo\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_karo\", \n"
"            \"col14\": \"widget_icon_karo\", \n"
"            \"col15\": \"widget_icon_karo\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_karo\", \n"
"            \"col18\": \"widget_icon_karo\", \n"
"            \"col19\": \"widget_icon_karo\", \n"
"            \"col2\": \"widget_icon_karo\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_karo\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_karo\", \n"
"            \"col6\": \"widget_icon_karo\", \n"
"            \"col7\": \"widget_icon_karo\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_karo\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_icon_karo\", \n"
"            \"col10\": \"widget_icon_karo\", \n"
"            \"col11\": \"widget_icon_karo\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_karo\", \n"
"            \"col14\": \"widget_icon_karo\", \n"
"            \"col15\": \"widget_icon_karo\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_karo\", \n"
"            \"col18\": \"widget_icon_karo\", \n"
"            \"col19\": \"widget_icon_karo\", \n"
"            \"col2\": \"widget_icon_karo\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_karo\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_karo\", \n"
"            \"col6\": \"widget_icon_karo\", \n"
"            \"col7\": \"widget_icon_karo\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_karo\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_icon_karo\", \n"
"            \"col10\": \"widget_icon_karo\", \n"
"            \"col11\": \"widget_icon_karo\", \n"
"            \"col12\": \"widget_icon_karo\", \n"
"            \"col13\": \"widget_icon_karo\", \n"
"            \"col14\": \"widget_icon_karo\", \n"
"            \"col15\": \"widget_icon_karo\", \n"
"            \"col16\": \"widget_icon_karo\", \n"
"            \"col17\": \"widget_icon_karo\", \n"
"            \"col18\": \"widget_icon_karo\", \n"
"            \"col19\": \"widget_icon_karo\", \n"
"            \"col2\": \"widget_icon_karo\", \n"
"            \"col20\": \"widget_icon_karo\", \n"
"            \"col3\": \"widget_icon_karo\", \n"
"            \"col4\": \"widget_icon_karo\", \n"
"            \"col5\": \"widget_icon_karo\", \n"
"            \"col6\": \"widget_icon_karo\", \n"
"            \"col7\": \"widget_icon_karo\", \n"
"            \"col8\": \"widget_icon_karo\", \n"
"            \"col9\": \"widget_icon_karo\"\n"
"        }, \n"
"        \"transition\": \"D\"\n"
"    }, \n"
"    \"layout_marquee1\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_marquee1\", \n"
"            \"col11\": \"widget_gif_marquee1\", \n"
"            \"col13\": \"widget_gif_marquee1\", \n"
"            \"col15\": \"widget_gif_marquee1\", \n"
"            \"col17\": \"widget_gif_marquee1\", \n"
"            \"col19\": \"widget_gif_marquee1\", \n"
"            \"col3\": \"widget_gif_marquee1\", \n"
"            \"col5\": \"widget_gif_marquee1\", \n"
"            \"col7\": \"widget_gif_marquee1\", \n"
"            \"col9\": \"widget_gif_marquee1\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_gif_marquee1\", \n"
"            \"col12\": \"widget_wlan0_short_bar\", \n"
"            \"col19\": \"widget_gif_marquee1\", \n"
"            \"col3\": \"widget_wlan0_label\", \n"
"            \"col9\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_gif_marquee1\", \n"
"            \"col19\": \"widget_gif_marquee1\", \n"
"            \"col3\": \"widget_bottom_marquee\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_gif_marquee1\", \n"
"            \"col11\": \"widget_gif_marquee1\", \n"
"            \"col13\": \"widget_gif_marquee1\", \n"
"            \"col15\": \"widget_gif_marquee1\", \n"
"            \"col17\": \"widget_gif_marquee1\", \n"
"            \"col19\": \"widget_gif_marquee1\", \n"
"            \"col3\": \"widget_gif_marquee1\", \n"
"            \"col5\": \"widget_gif_marquee1\", \n"
"            \"col7\": \"widget_gif_marquee1\", \n"
"            \"col9\": \"widget_gif_marquee1\"\n"
"        },\n"
"        \"transition\": \"B\"\n"
"    }, \n"
"    \"layout_marquee2\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_marquee2\", \n"
"            \"col11\": \"widget_gif_marquee2\", \n"
"            \"col13\": \"widget_gif_marquee2\", \n"
"            \"col15\": \"widget_gif_marquee2\", \n"
"            \"col17\": \"widget_gif_marquee2\", \n"
"            \"col19\": \"widget_gif_marquee2\", \n"
"            \"col3\": \"widget_gif_marquee2\", \n"
"            \"col5\": \"widget_gif_marquee2\", \n"
"            \"col7\": \"widget_gif_marquee2\", \n"
"            \"col9\": \"widget_gif_marquee2\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_gif_marquee2\", \n"
"            \"col12\": \"widget_wlan0_short_bar\", \n"
"            \"col19\": \"widget_gif_marquee2\", \n"
"            \"col3\": \"widget_wlan0_label\", \n"
"            \"col9\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_gif_marquee2\", \n"
"            \"col19\": \"widget_gif_marquee2\", \n"
"            \"col3\": \"widget_bottom_marquee\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_gif_marquee2\", \n"
"            \"col11\": \"widget_gif_marquee2\", \n"
"            \"col13\": \"widget_gif_marquee2\", \n"
"            \"col15\": \"widget_gif_marquee2\", \n"
"            \"col17\": \"widget_gif_marquee2\", \n"
"            \"col19\": \"widget_gif_marquee2\", \n"
"            \"col3\": \"widget_gif_marquee2\", \n"
"            \"col5\": \"widget_gif_marquee2\", \n"
"            \"col7\": \"widget_gif_marquee2\", \n"
"            \"col9\": \"widget_gif_marquee2\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    }, \n"
"    \"layout_marquee3\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_marquee3\", \n"
"            \"col11\": \"widget_gif_marquee3\", \n"
"            \"col13\": \"widget_gif_marquee3\", \n"
"            \"col15\": \"widget_gif_marquee3\", \n"
"            \"col17\": \"widget_gif_marquee3\", \n"
"            \"col19\": \"widget_gif_marquee3\", \n"
"            \"col3\": \"widget_gif_marquee3\", \n"
"            \"col5\": \"widget_gif_marquee3\", \n"
"            \"col7\": \"widget_gif_marquee3\", \n"
"            \"col9\": \"widget_gif_marquee3\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_gif_marquee3\", \n"
"            \"col12\": \"widget_wlan0_short_bar\", \n"
"            \"col19\": \"widget_gif_marquee3\", \n"
"            \"col3\": \"widget_wlan0_label\", \n"
"            \"col9\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_gif_marquee3\", \n"
"            \"col19\": \"widget_gif_marquee3\", \n"
"            \"col3\": \"widget_bottom_marquee\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_gif_marquee3\", \n"
"            \"col11\": \"widget_gif_marquee3\", \n"
"            \"col13\": \"widget_gif_marquee3\", \n"
"            \"col15\": \"widget_gif_marquee3\", \n"
"            \"col17\": \"widget_gif_marquee3\", \n"
"            \"col19\": \"widget_gif_marquee3\", \n"
"            \"col3\": \"widget_gif_marquee3\", \n"
"            \"col5\": \"widget_gif_marquee3\", \n"
"            \"col7\": \"widget_gif_marquee3\", \n"
"            \"col9\": \"widget_gif_marquee3\"\n"
"        },\n"
"        \"transition\": \"D\"\n"
"    }, \n"
"    \"layout_marquee4\": {\n"
"        \"row1\": {\n"
"            \"col1\": \"widget_gif_marquee4\", \n"
"            \"col11\": \"widget_gif_marquee4\", \n"
"            \"col13\": \"widget_gif_marquee4\", \n"
"            \"col15\": \"widget_gif_marquee4\", \n"
"            \"col17\": \"widget_gif_marquee4\", \n"
"            \"col19\": \"widget_gif_marquee4\", \n"
"            \"col3\": \"widget_gif_marquee4\", \n"
"            \"col5\": \"widget_gif_marquee4\", \n"
"            \"col7\": \"widget_gif_marquee4\", \n"
"            \"col9\": \"widget_gif_marquee4\"\n"
"        }, \n"
"        \"row2\": {\n"
"            \"col1\": \"widget_gif_marquee4\", \n"
"            \"col12\": \"widget_wlan0_short_bar\", \n"
"            \"col19\": \"widget_gif_marquee4\", \n"
"            \"col3\": \"widget_wlan0_label\", \n"
"            \"col9\": \"widget_wlan0\"\n"
"        }, \n"
"        \"row3\": {\n"
"            \"col1\": \"widget_gif_marquee4\", \n"
"            \"col19\": \"widget_gif_marquee4\", \n"
"            \"col3\": \"widget_bottom_marquee\"\n"
"        }, \n"
"        \"row4\": {\n"
"            \"col1\": \"widget_gif_marquee4\", \n"
"            \"col11\": \"widget_gif_marquee4\", \n"
"            \"col13\": \"widget_gif_marquee4\", \n"
"            \"col15\": \"widget_gif_marquee4\", \n"
"            \"col17\": \"widget_gif_marquee4\", \n"
"            \"col19\": \"widget_gif_marquee4\", \n"
"            \"col3\": \"widget_gif_marquee4\", \n"
"            \"col5\": \"widget_gif_marquee4\", \n"
"            \"col7\": \"widget_gif_marquee4\", \n"
"            \"col9\": \"widget_gif_marquee4\"\n"
"        },\n"
"        \"transition\": \"U\"\n"
"    }, \n"
"    \"plugins\": {\n"
"        \"i2c_sensors-path\": \"/sys/bus/i2c/devices/1-0028/\"\n"
"    }, \n"
"    \"widget_superscope\": {\n"
"        \"init\": [\n"
"  \"n=500\",\n"
"  \"r=10\",\n"
"  \"mx=0\",\n"
"  \"my=0\",\n"
"  \"mz=0\",\n"
"  \"dst=0.2\",\n"
"  \"rx=0\",\n"
"  \"ry=0\",\n"
"  \"rz=0\",\n"
"  \"rdx=1\",\n"
"  \"rdy=1\",\n"
"  \"rdz=1\",\n"
"  \"p=3.14159265\",\n"
"  \"p2=10.0*p\",\n"
"  \"p3=50/p\"\n"
"\n"
"        ],\n"
"        \"frame\": [\n"
"  \"rx=rx+rdx\",\n"
"  \"ry=ry+rdy\",\n"
"  \"rz=rz+rdz\",\n"
"  \"xs=sin(rx/p3)\",\n"
"  \"ys=sin(ry/p3)\",\n"
"  \"zs=sin(rz/p3)\",\n"
"  \"xc=cos(rx/p3)\",\n"
"  \"yc=cos(ry/p3)\",\n"
"  \"zc=cos(rz/p3)\"\n"
"        ],\n"
"        \"beat\": [\n"
"  \"r=rand(8) + 2\"\n"
"        ],\n"
"        \"point\": [\n"
"  \"x1=v*sin(p2*i)\",\n"
"  \"y1=v * i / cos(z1)\",\n"
"  \"z1=r*cos(p2*i)\",\n"
"  \"y2=y1*xc-z1*xs\",\n"
"  \"z2=y1*xs+z1*xc\",\n"
"  \"x2=z2*ys+x1*yc\",\n"
"  \"z3=z2*yc-x1*ys\",\n"
"  \"x3=x2*zc-y2*zs\",\n"
"  \"y3=y2*zc+x2*zs\",\n"
"  \"x4=mx+x3\",\n"
"  \"y4=my+y3\",\n"
"  \"z4=mz+z3\",\n"
"  \"x=x4/(1+z4/dst)\",\n"
"  \"y=y4/(1+z4/dst)\"\n"
"\n"
"        ]\n"
"    },\n"
"    \"widget_page_label\": {\n"
"        \"type\": \"text\",\n"
"        \"length\": 10,\n"
"        \"expression\": \"return 'PAGE FILE:'\"\n"
"    },\n"
"    \"widged_page\": {\n"
"        \"type\": \"text\",\n"
"        \"length\": 6,\n"
"        \"expression\": \"return procstat.ProcStat('page')\"\n"
"    },\n"
"    \"widget_histogram_large\": {\n"
"        \"type\": \"histogram\",\n"
"        \"expression\": \"return procstat.Cpu('busy', 500)\",\n"
"        \"foreground\": \"99005500\",\n"
"        \"background\": \"77777777\",\n"
"        \"height\": 32,\n"
"        \"width\": 160,\n"
"        \"update\": 100\n"
"    },\n"
"    \"widget_hddtemp\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'IDE Temp: ' .. exec.Exec('hddtemp /dev/sda1 | cut -f 3 -d :', 999)\",\n"
"        \"length\": 14,\n"
"        \"align\": \"L\",\n"
"        \"update\": 999\n"
"    },\n"
"    \"widget_FSSpace\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"fsspace_a = ((statfs.Statfs('/', 'bavail')*statfs.Statfs('/', 'bsize'))/ 1024/ 1024);fsspace_b = ((statfs.Statfs('/', 'bavail')*statfs.Statfs('/', 'bsize'))/1024/1024);c = '/ ' .. fsspace_a .. 'MB / ' .. fsspace_b .. ' MB'; return c;\n"
"        \",\n"
"        \"length\": 42,\n"
"        \"align\": \"M\",\n"
"        \"speed\": 30\n"
"    },\n"
"    \"widget_CPU\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return procstat.Cpu('busy', 500)\",\n"
"        \"postfix\": \"return '% '\",\n"
"        \"length\": 5,\n"
"        \"precision\": 1,\n"
"        \"align\": \"R\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_CPUBar\": {\n"
"        \"type\": \"bar\",\n"
"        \"expression\": \"return procstat.Cpu('busy', 500)\",\n"
"        \"expression2\": \"return procstat.Cpu('system', 500)\",\n"
"        \"length\": 10,\n"
"        \"min\": \"1\",\n"
"        \"max\": \"100\",\n"
"        \"direction\": \"E\",\n"
"        \"style\": \"H\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_CPULabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'CPU:'\",\n"
"        \"length\": 4,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_RAMTotal\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return meminfo.Meminfo('MemTotal')/1024\",\n"
"        \"postfix\": \"return 'MB FREE'\",\n"
"        \"length\": 11,\n"
"        \"precision\": 0,\n"
"        \"align\": \"L\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_RAMFree\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return meminfo.Meminfo('MemFree')/1024\",\n"
"        \"postfix\": \"return '/'\",\n"
"        \"length\": 5,\n"
"        \"precision\": 0,\n"
"        \"align\": \"R\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_RAMLabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'RAM:'\",\n"
"        \"length\": 4,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_IDEIn\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return diskstats.Diskstats('sda', 'read_sectors', 100)/2048\",\n"
"        \"prefix\": \"return 'In '\",\n"
"        \"postfix\": \"return 'MB'\",\n"
"        \"precision\": 2,\n"
"        \"align\": \"R\",\n"
"        \"length\": 10,\n"
"        \"update\": 500\n"
"    },\n"
"    \"widget_IDEOut\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return diskstats.Diskstats('sda', 'write_sectors', 100)/2048\",\n"
"        \"prefix\": \"return 'Out'\",\n"
"        \"postfix\": \"return 'MB'\",\n"
"        \"precision\": 2,\n"
"        \"align\": \"R\",\n"
"        \"length\": 10,\n"
"        \"update\": 500\n"
"    },\n"
"    \"widget_IDEBar\": {\n"
"        \"type\": \"bar\",\n"
"        \"expression\": \"return diskstats.Diskstats('sda', 'read_sectors', 100)\",\n"
"        \"expression2\": \"return diskstats.Diskstats('sda', 'write_sectors', 100)\",\n"
"        \"length\": 14,\n"
"        \"direction\": \"E\",\n"
"        \"style\": \"H\",\n"
"        \"update\": 500\n"
"    },\n"
"    \"widget_IDELabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'IDE:'\",\n"
"        \"length\": 4,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_WLANLabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'WLAN:'\",\n"
"        \"length\": 5,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_WLANIn\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return netdev.Fast('wlan0', 'Rx_bytes', 500)/1024\",\n"
"        \"prefix\": \"'OUT'\",\n"
"        \"postfix\": \"'KB'\",\n"
"        \"length\": 9,\n"
"        \"precision\": 0,\n"
"        \"align\": \"R\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_WLANOut\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return netdev.Fast('wlan0', 'Tx_bytes', 500)/1024\",\n"
"        \"prefix\": \"'IN'\",\n"
"        \"postfix\": \"'KB'\",\n"
"        \"length\": 9,\n"
"        \"precision\": 0,\n"
"        \"align\": \"R\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_WLANBar\": {\n"
"        \"type\": \"bar\",\n"
"        \"expression\": \"return netdev.Fast('wlan0', 'Rx_bytes', 500)\",\n"
"        \"expression2\": \"return netdev.Fast('wlan0', 'Tx_bytes', 500)\",\n"
"        \"length\": 14,\n"
"        \"direction\": \"E\",\n"
"        \"style\": \"H\",\n"
"        \"update\": 50\n"
"    },\n"
"    \"widget_TimeLabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'TIME:'\",\n"
"        \"length\": 5,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_Time\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return time.Strftime('%a,%m/%d %H:%M:%S', time.Time())\",\n"
"        \"length\": 20,\n"
"        \"align\": \"C\",\n"
"        \"update\": 10\n"
"    },\n"
"    \"widget_UptimeLabel\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return 'UPTIME:'\",\n"
"        \"length\": 7,\n"
"        \"align\": \"L\",\n"
"        \"bold\": 1\n"
"    },\n"
"    \"widget_Uptime\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return uptime.Uptime('%d d %H:%M:%S')\",\n"
"        \"length\": 21,\n"
"        \"align\": \"L\",\n"
"        \"update\": 999\n"
"    },\n"
"    \"widget_fps\": {\n"
"        \"type\": \"text\",\n"
"        \"expression\": \"return fps.avg() .. ' - FPS'\",\n"
"        \"length\": 11,\n"
"        \"foreground\": \"FFFFFFFF\",\n"
"        \"background\": \"ff000000\"\n"
"    },\n"
"    \"widget_vis_banner\": {\n"
"        \"type\": \"filter\",\n"
"        \"width\": 48,\n"
"        \"height\": 16,\n"
"        \"update\": 100,\n"
"        \"actor\": \"dmovement\",\n"
"        \"style\": \"pcm\"\n"
"    },\n"
"    \"widget_infinite_256x64\": {\n"
"        \"type\": \"visualization\",\n"
"        \"width\": 256,\n"
"        \"height\": 64,\n"
"        \"update\": 50,\n"
"        \"morph-timeout\": 5500,\n"
"        \"morph-steps\": 5,\n"
"        \"skip-actors\": \"gstreamer:gdkpixbuf:lcdcontrol:jess:oinksie:goom2k4:jakdaw\",\n"
"        \"actor\": \"corona\",\n"
"        \"input\": \"debug\",\n"
"        \"morph\": \"slide_up\",\n"
"        \"style\": \"pcm\",\n"
"        \"alpha\": 50\n"
"    },\n"
"    \"widget_libvisual_256x64\": {\n"
"        \"type\": \"visualization\",\n"
"        \"width\": 256,\n"
"        \"height\": 64,\n"
"        \"update\": 50,\n"
"        \"morph-timeout\": 0,\n"
"        \"morph-steps\": 18,\n"
"        \"skip-actors\": \"gstreamer:gdkpixbuf:lcdcontrol:jess:oinksie:goom2k4:jakdaw\",\n"
"        \"actor\": \"lv_analyzer\",\n"
"        \"input\": \"debug\",\n"
"        \"morph\": \"tentacle\",\n"
"        \"style\": \"pcm\",\n"
"        \"alpha\": 50,\n"
"        \"params\": {\n"
"            \"oinksie\": {\n"
"                \"acid palette\": 1,\n"
"                \"color mode\": 4\n"
"            },\n"
"            /*\"blursk\": { // blur scope\n"
"                \"show_info\": \"Always\",\n"
"                \"show_timestamp\": 1,\n"
"                \"color\": \"r=246,g=242,b=20\",\n"
"                \"color_style\": \"Dimming\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Simple\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Oscilloscope\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\",\n"
"                \"beat_sensitivity\": 4\n"
"            },*/\n"
"            \"blursk\": { // box spectrum\n"
"                \"color\": \"r=0,g=254,b=0\",\n"
"                \"color_style\": \"Flame\",\n"
"                \"signal_color\": \"White signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Backward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Edges\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Dark bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            /*\"blursk\": { // burning logo\n"
"                \"color\": \"r=254,g=98,b=38\",\n"
"                \"color_style\": \"Flame\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Cylinder\",\n"
"                \"transition_speed\": \"Slow switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"Blursk stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Airbrush\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Blursk flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"TRUE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },*/\n"
"            /*\"blursk\": { // cat scan\n"
"                \"color\": \"r=175,g=245,b=0\",\n"
"                \"color_style\": \"Rainbow\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Fast fade\",\n"
"                \"blur_style\": \"Four way\",\n"
"                \"transition_speed\": \"Fast switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Radial spectrum\",\n"
"                \"plot_style\": \"Airbrush\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Ripple effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },*/\n"
"            /*\"blursk\": { // cubism\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Color stripes\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Tangram\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Melt\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Mirrored\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Invert flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Dark bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // fan\n"
"                \"color\": \"r=0,g=255,b=0\",\n"
"                \"color_style\": \"Milky\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Four way\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"No blur\",\n"
"                \"blur_stencil\": \"Tux stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Radar\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // flag\n"
"                \"color\": \"r=0,g=255,b=255\",\n"
"                \"color_style\": \"Color bands\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Random\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Radar\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // flame scan\n"
"                \"color\": \"r=242,g=74,b=0\",\n"
"                \"color_style\": \"Flame\",\n"
"                \"signal_color\": \"White signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Flow around\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Edges\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Ripple effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // flashbulb\n"
"                \"color\": \"r=0,g=178,b=246\",\n"
"                \"color_style\": \"Dimming\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 1,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Prismatic\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Melt\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"None\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Random flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // foil\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // frenetic\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Graying\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Fast fade\",\n"
"                \"blur_style\": \"Fast forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Phase shift\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Flash bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // heat wave\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Color layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Rise\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"black_background\": \"TRUE\",\n"
"                \"toggle_bpl\": \"Edge smooth\",\n"
"                \"background\": \"White bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // interference\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Color stripes\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 1,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Mirrored\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // lens\n"
"                \"color\": \"r=249,g=69,b=0\",\n"
"                \"color_style\": \"Milky\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Ripple\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Mirrored\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // metalic\n"
"                \"color\": \"r=0,g=253,b=253\",\n"
"                \"color_style\": \"Metal\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Random slow\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Oscilloscope\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Bump effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"black_background\": \"TRUE\",\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // nucleus\n"
"                \"color\": \"r=11,g=253,b=249\",\n"
"                \"color_style\": \"Color stripes\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 1,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Fast forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Phase shift\",\n"
"                \"plot_style\": \"Fuzzy dots\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"black_background\": \"TRUE\",\n"
"                \"toggle_bpl\": \"Edge smooth\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // quick change\n"
"                \"color\": \"r=250,g=129,b=253\",\n"
"                \"color_style\": \"Standoff\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Random\",\n"
"                \"transition_speed\": \"Fast switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Radar\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // random flower\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Random\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Random slow\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Random bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // random mirrored spectrum\n"
"                \"color\": \"r=252,g=154,b=10\",\n"
"                \"color_style\": \"Random\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Random slow\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Mirrored\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Random flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Random bkgnd\",\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // ripple\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Color stripes\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Random\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"High/Low plot\",\n"
"                \"plot_style\": \"Starburst\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Shift bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // roller\n"
"                \"color\": \"r=70,g=0,b=251\",\n"
"                \"color_style\": \"Stripes\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 1,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Cylinder\",\n"
"                \"transition_speed\": \"Fast switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Airbrush\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // rose\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Rainbow\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Tangram\",\n"
"                \"transition_speed\": \"Slow switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"White bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // scan\n"
"                \"color\": \"r=175,g=245,b=0\",\n"
"                \"color_style\": \"Rainbow\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Flow around\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"None\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Invert flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"random_dots\": \"TRUE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"Slow floaters\"\n"
"            },\n"
"            \"blursk\": { // sparkler\n"
"                \"color\": \"r=252,g=72,b=0\",\n"
"                \"color_style\": \"Metal\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Four way\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Radar\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // subliminal logo\n"
"                \"color\": \"r=175,g=245,b=0\",\n"
"                \"color_style\": \"Random\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Random\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Random blur\",\n"
"                \"blur_stencil\": \"Random stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"Random flash\",\n"
"                \"overall_effect\": \"Ripple effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // tunnel\n"
"                \"color\": \"r=179,g=251,b=0\",\n"
"                \"color_style\": \"Color layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // tunnel2\n"
"                \"color\": \"r=245,g=68,b=0\",\n"
"                \"color_style\": \"Color layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Fast forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Dark bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // wiggler\n"
"                \"color\": \"r=0,g=253,b=253\",\n"
"                \"color_style\": \"Color layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Flow around\",\n"
"                \"transition_speed\": \"Fast switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Radial spectrum\",\n"
"                \"plot_style\": \"Starburst\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Dark bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // xmms\n"
"                \"color\": \"r=0,g=254,b=254\",\n"
"                \"color_style\": \"Dimming\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Random\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"XMMS stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Flower\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"XMMS flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Color bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // bump scope\n"
"                \"color\": \"r=246,g=240,b=10\",\n"
"                \"color_style\": \"Dimming\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Simple\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Oscilloscope\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Bump effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // wax\n"
"                \"color\": \"r=38,g=246,b=9\",\n"
"                \"color_style\": \"Flame\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"fade_speed\": \"Fast fade\",\n"
"                \"blur_style\": \"Gravity\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Oscilloscope\",\n"
"                \"plot_style\": \"Line\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"White bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // gas cloud\n"
"                \"color\": \"r=247,g=128,b=0\",\n"
"                \"color_style\": \"Color layers\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Flow between\",\n"
"                \"transition_speed\": \"Fast switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Radial spectrum\",\n"
"                \"plot_style\": \"Starburst\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Ripple effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Shift bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // aurora\n"
"                \"color\": \"r=251,g=205,b=2\",\n"
"                \"color_style\": \"Color standoff\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Forward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Radial spectrum\",\n"
"                \"plot_style\": \"Inertia\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // fractal drums\n"
"                \"color\": \"r=255,g=234,b=0\",\n"
"                \"color_style\": \"Brightening\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Fractal sphere\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"signal_style\": \"Phase shift\",\n"
"                \"plot_style\": \"Fuzzy dots\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Bump effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"toggle_bpl\": \"Edge smooth\",\n"
"                \"background\": \"Black bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // butterfly\n"
"                \"color\": \"r=0,g=254,b=0\",\n"
"                \"color_style\": \"Color standoff\",\n"
"                \"signal_color\": \"White signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Backward\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Smear\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Edges\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"FALSE\",\n"
"                \"background\": \"Shift bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // radioactive bob\n"
"                \"color\": \"r=248,g=248,b=0\",\n"
"                \"color_style\": \"Milky\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 1,\n"
"                \"black_background\": \"FALSE\",\n"
"                \"fade_speed\": \"Medium fade\",\n"
"                \"blur_style\": \"Tangram\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"Bob stencil\",\n"
"                \"slow_motion\": 1,\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"signal_style\": \"Phase shift\",\n"
"                \"plot_style\": \"None\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"Bob flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"random_dots\": \"TRUE\",\n"
"                \"background\": \"Color bkgnd\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },\n"
"            \"blursk\": { // testing 1 2 3\n"
"                \"color\": \"r=237,g=5,b=230\",\n"
"                \"color_style\": \"Flame\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"background\": \"Random bkgnd\",\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Random slow\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Full blur\",\n"
"                \"blur_stencil\": \"Maybe stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"toggle_bpl\": \"Area smooth\",\n"
"                \"signal_style\": \"Mono spectrum\",\n"
"                \"plot_style\": \"Inertia\",\n"
"                \"thick_on_beats\": 0,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Normal effect\",\n"
"                \"floaters\": \"Fast floaters\"\n"
"            },\n"
"            \"blursk\": { // drain\n"
"                \"color\": \"r=228,g=150,b=0\",\n"
"                \"color_style\": \"Rainbow\",\n"
"                \"signal_color\": \"Normal signal\",\n"
"                \"contour_lines\": 0,\n"
"                \"hue_on_beats\": 0,\n"
"                \"background\": \"Color bkgnd\",\n"
"                \"fade_speed\": \"Slow fade\",\n"
"                \"blur_style\": \"Drain\",\n"
"                \"transition_speed\": \"Medium switch\",\n"
"                \"blur_when\": \"Reduced blur\",\n"
"                \"blur_stencil\": \"No stencil\",\n"
"                \"slow_motion\": 0,\n"
"                \"signal_style\": \"Stereo spectrum\",\n"
"                \"plot_style\": \"Edges\",\n"
"                \"thick_on_beats\": 1,\n"
"                \"flash_style\": \"No flash\",\n"
"                \"overall_effect\": \"Anti-fade effect\",\n"
"                \"floaters\": \"No floaters\"\n"
"            },*/\n"
"            \"none\": {}\n"
"        }\n"
"    },\n"
"    \"widget_pcm_24x16\": {\n"
"        \"type\": \"visualization\",\n"
"        \"width\": 24,\n"
"        \"height\": 16,\n"
"        \"update\": 100,\n"
"        \"style\": \"pcm\",\n"
"        \"actor\": \"oinksie\",\n"
"        \"morph-timeout\": 0,\n"
"        \"skip-actors\": \"gstreamer:gdkpixbuf:jakdaw\"\n"
"    },\n"
"    \"widget_peak\": {\n"
"        \"type\": \"visualization\",\n"
"        \"width\": 20,\n"
"        \"height\": 4,\n"
"        \"update\": 100,\n"
"        \"style\": \"peak\"\n"
"    },\n"
"    \"widget_spectrum\": {\n"
"        \"type\": \"visualization\",\n"
"        \"width\": 20,\n"
"        \"height\": 4,\n"
"        \"update\": 100,\n"
"        \"style\": \"spectrum\"\n"
"    },\n"
"    \"widget_bignums\": {\n"
"        \"expression\": \"return procstat.Cpu('busy', 200) \", \n"
"        \"type\": \"bignums\", \n"
"        \"max\": 100,\n"
"        \"min\": 0,\n"
"        \"update\": 1,\n"
"        \"foreground\": \"ffFFFFFF\",\n"
"        \"background\": \"00ffffff\"\n"
"    }, \n"
"    \"widget_cpuinfo_label\": {\n"
"        \"expression\": \"return 'CPUInfo:  '\",\n"
"        \"type\": \"text\",\n"
"        \"length\": 10\n"
"    },\n"
"    \"widget_cpuinfo\": {\n"
"        \"expression\": \"return cpuinfo.Cpuinfo('model name') .. '     '\",\n"
"        \"type\": \"text\",\n"
"        \"length\": 10\n"
"    },\n"
"    \"widget_bottom_marquee\": {\n"
"        \"align\": \"M\", \n"
"        \"expression\": \"uname.Uname('sysname') + ' ' + uname.Uname('nodename') + ' ' + uname.Uname('release') + ' ' + cpuinfo.Cpuinfo('model name')\", \n"
"        \"type\": \"text\", \n"
"        \"speed\": 100, \n"
"        \"length\": 16\n"
"    }, \n"
"    \"widget_bottom_ticker\": {\n"
"        \"align\": \"P\", \n"
"        \"expression\": \"uname.Uname('sysname') + ' ' + uname.Uname('nodename') + ' ' + uname.Uname('release') + ' ' + cpuinfo.Cpuinfo('model name')\", \n"
"        \"type\": \"text\", \n"
"        \"speed\": 100,\n"
"        \"bold\": 1,\n"
"        \"length\": 42\n"
"    }, \n"
"    \"widget_percent\": {\n"
"        \"expression\": \"return '%'\",\n"
"        \"length\": 1\n"
"    },\n"
"    \"widget_cpu\": {\n"
"        \"align\": \"R\", \n"
"        \"expression\": \"procstat.Cpu('busy', 500)\", \n"
"        \"postfix\": \"'%'\", \n"
"        \"precision\": 0, \n"
"        \"type\": \"text\", \n"
"        \"update\": 500, \n"
"        \"length\": 5\n"
"    }, \n"
"    \"widget_cpu_bar\": {\n"
"        \"direction\": \"W\", \n"
"        \"expression\": \"procstat.Cpu('busy', 500)\", \n"
"        \"length\": 10, \n"
"        \"max\": \"100\", \n"
"        \"min\": \"0\", \n"
"        \"style\": \"H\", \n"
"        \"type\": \"bar\", \n"
"        \"update\": 500\n"
"    }, \n"
"    \"widget_cpu_histogram\": {\n"
"        \"direction\": \"E\", \n"
"        \"expression\": \"procstat.Cpu('busy', 500)\", \n"
"        \"gap\": 1, \n"
"        \"length\": 10, \n"
"        \"max\": \"100\", \n"
"        \"min\": \"0\", \n"
"        \"type\": \"histogram\", \n"
"        \"update\": 500\n"
"    }, \n"
"    \"widget_cpu_label\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"return 'CPU:'\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 4\n"
"    }, \n"
"    \"widget_dow\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"\", \n"
"        \"type\": \"text\"\n"
"    }, \n"
"    \"widget_dow_end\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 1\n"
"    }, \n"
"    \"widget_dow_label\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"'Ambient:'\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 10\n"
"    }, \n"
"    \"widget_gif_american_flag\": {\n"
"        \"file\": \"gifs/American_Flag_ani.gif\", \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\", \n"
"        \"xpoint\": 1,\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_bolt\": {\n"
"        \"file\": \"gifs/lightning_bolt_ani.gif\", \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\",\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_intel\": {\n"
"        \"file\": \"gifs/intel_logo_ani.gif\", \n"
"        \"start\": 1, \n"
"        \"end\": 6, \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\",\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_marquee1\": {\n"
"        \"file\": \"gifs/marquee1.gif\", \n"
"        \"height\": 8, \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\", \n"
"        \"width\": 12,\n"
"        \"height\": 12,\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_marquee2\": {\n"
"        \"file\": \"gifs/marquee2.gif\", \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\",\n"
"        \"widget\": 12,\n"
"        \"height\": 12,\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_marquee3\": {\n"
"        \"file\": \"gifs/marquee3.gif\", \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\",\n"
"        \"widget\": 12,\n"
"        \"height\": 12,\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_gif_marquee4\": {\n"
"        \"file\": \"gifs/marquee4.gif\", \n"
"        \"type\": \"gif\", \n"
"        \"update\": \"250\",\n"
"        \"widget\": 12,\n"
"        \"height\": 12,\n"
"        \"inverted\": 1\n"
"    }, \n"
"    \"widget_icon_blob\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....\", \n"
"            \"row2\": \".....|.....|.***.\", \n"
"            \"row3\": \".....|.***.|*...*\", \n"
"            \"row4\": \"..*..|.*.*.|*...*\", \n"
"            \"row5\": \".....|.***.|*...*\", \n"
"            \"row6\": \".....|.....|.***.\", \n"
"            \"row7\": \".....|.....|.....\", \n"
"            \"row8\": \".....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 300, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_ekg\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....|.....|.....|.....|.....|.....\", \n"
"            \"row2\": \".....|....*|...*.|..*..|.*...|*....|.....|.....\", \n"
"            \"row3\": \".....|....*|...*.|..*..|.*...|*....|.....|.....\", \n"
"            \"row4\": \".....|....*|...**|..**.|.**..|**...|*....|.....\", \n"
"            \"row5\": \".....|....*|...**|..**.|.**..|**...|*....|.....\", \n"
"            \"row6\": \".....|....*|...*.|..*.*|.*.*.|*.*..|.*...|*....\", \n"
"            \"row7\": \"*****|*****|****.|***..|**..*|*..**|..***|.****\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 30, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_heart\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....|.....|.....|.....\", \n"
"            \"row2\": \".*.*.|.....|.*.*.|.....|.....|.....\", \n"
"            \"row3\": \"*****|.*.*.|*****|.*.*.|.*.*.|.*.*.\", \n"
"            \"row4\": \"*****|.***.|*****|.***.|.***.|.***.\", \n"
"            \"row5\": \".***.|.***.|.***.|.***.|.***.|.***.\", \n"
"            \"row6\": \".***.|..*..|.***.|..*..|..*..|..*..\", \n"
"            \"row7\": \"..*..|.....|..*..|.....|.....|.....\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 500, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_heartbeat\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....\", \n"
"            \"row2\": \".*.*.|.*.*.\", \n"
"            \"row3\": \"*****|*.*.*\", \n"
"            \"row4\": \"*****|*...*\", \n"
"            \"row5\": \".***.|.*.*.\", \n"
"            \"row6\": \".***.|.*.*.\", \n"
"            \"row7\": \"..*..|..*..\", \n"
"            \"row8\": \".....|.....\"\n"
"        }, \n"
"        \"speed\": 500, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_karo\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....|.....|..*..|.....|.....|.....\", \n"
"            \"row2\": \".....|.....|.....|..*..|.*.*.|..*..|.....|.....\", \n"
"            \"row3\": \".....|.....|..*..|.*.*.|*...*|.*.*.|..*..|.....\", \n"
"            \"row4\": \".....|..*..|.*.*.|*...*|.....|*...*|.*.*.|..*..\", \n"
"            \"row5\": \".....|.....|..*..|.*.*.|*...*|.*.*.|..*..|.....\", \n"
"            \"row6\": \".....|.....|.....|..*..|.*.*.|..*..|.....|.....\", \n"
"            \"row7\": \".....|.....|.....|.....|..*..|.....|.....|.....\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 100, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_rain\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \"...*.|.....|.....|.*...|....*|..*..|.....|*....\", \n"
"            \"row2\": \"*....|...*.|.....|.....|.*...|....*|..*..|.....\", \n"
"            \"row3\": \".....|*....|...*.|.....|.....|.*...|....*|..*..\", \n"
"            \"row4\": \"..*..|.....|*....|...*.|.....|.....|.*...|....*\", \n"
"            \"row5\": \"....*|..*..|.....|*....|...*.|.....|.....|.*...\", \n"
"            \"row6\": \".*...|....*|..*..|.....|*....|...*.|.....|.....\", \n"
"            \"row7\": \".....|.*...|....*|..*..|.....|*....|...*.|.....\", \n"
"            \"row8\": \".....|.....|.*...|....*|..*..|.....|*....|...*.\"\n"
"        }, \n"
"        \"speed\": 100, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_squirrel\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....|.....|.....|.....\", \n"
"            \"row2\": \".....|.....|.....|.....|.....|.....\", \n"
"            \"row3\": \".....|.....|.....|.....|.....|.....\", \n"
"            \"row4\": \"**...|.**..|..**.|...**|....*|.....\", \n"
"            \"row5\": \"*****|*****|*****|*****|*****|*****\", \n"
"            \"row6\": \"...**|..**.|.**..|**...|*....|.....\", \n"
"            \"row7\": \".....|.....|.....|.....|.....|.....\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 100, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_timer\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \".....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|\", \n"
"            \"row2\": \".***.|.*+*.|.*++.|.*++.|.*++.|.*++.|.*++.|.*++.|.*++.|.*++.|.*++.|.*++.|.+++.|.+*+.|.+**.|.+**.|.+**.|.+**.|.+**.|.+**.|.+**.|.+**.|.+**.|.+**.|\", \n"
"            \"row3\": \"*****|**+**|**++*|**+++|**++.|**++.|**+++|**+++|**+++|**+++|**+++|+++++|+++++|++*++|++**+|++***|++**.|++**.|++***|++***|++***|++***|++***|*****|\", \n"
"            \"row4\": \"*****|**+**|**+**|**+**|**+++|**+++|**+++|**+++|**+++|**+++|+++++|+++++|+++++|++*++|++*++|++*++|++***|++***|++***|++***|++***|++***|*****|*****|\", \n"
"            \"row5\": \"*****|*****|*****|*****|*****|***++|***++|**+++|*++++|+++++|+++++|+++++|+++++|+++++|+++++|+++++|+++++|+++**|+++**|++***|+****|*****|*****|*****|\", \n"
"            \"row6\": \".***.|.***.|.***.|.***.|.***.|.***.|.**+.|.*++.|.+++.|.+++.|.+++.|.+++.|.+++.|.+++.|.+++.|.+++.|.+++.|.+++.|.++*.|.+**.|.***.|.***.|.***.|.***.|\", \n"
"            \"row7\": \".....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|.....|\"\n"
"        }, \n"
"        \"speed\":  100, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_icon_wave\": {\n"
"        \"bitmap\": {\n"
"            \"row1\": \"..**.|.**..|**...|*....|.....|.....|.....|.....|....*|...**\", \n"
"            \"row2\": \".*..*|*..*.|..*..|.*...|*....|.....|.....|....*|...*.|..*..\", \n"
"            \"row3\": \"*....|....*|...*.|..*..|.*...|*....|....*|...*.|..*..|.*...\", \n"
"            \"row4\": \"*....|....*|...*.|..*..|.*...|*....|....*|...*.|..*..|.*...\", \n"
"            \"row5\": \"*....|....*|...*.|..*..|.*...|*....|....*|...*.|..*..|.*...\", \n"
"            \"row6\": \".....|.....|....*|...*.|..*..|.*..*|*..*.|..*..|.*...|*....\", \n"
"            \"row7\": \".....|.....|.....|....*|...**|..**.|.**..|**...|*....|.....\", \n"
"            \"row8\": \".....|.....|.....|.....|.....|.....|.....|.....|.....|.....\"\n"
"        }, \n"
"        \"speed\": 100, \n"
"        \"type\": \"icon\"\n"
"    }, \n"
"    \"widget_key_down\": {\n"
"        \"expression\": \"return lcd.Transition(-1)\", \n"
"        \"key\": 2, \n"
"        \"type\": \"key\"\n"
"    }, \n"
"    \"widget_key_up\": {\n"
"        \"expression\": \"return lcd.Transition(1)\", \n"
"        \"key\": 1, \n"
"        \"type\": \"key\"\n"
"    }, \n"
"    \"widget_percent\": {\n"
"        \"expression\": \"return '%'\", \n"
"        \"type\": \"text\"\n"
"    }, \n"
"    \"widget_ram_active\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"return meminfo.Meminfo('Active')/1024\", \n"
"        \"type\": \"text\", \n"
"        \"postfix\": \"'/'\",\n"
"        \"precision\": 0,\n"
"        \"update\": 500, \n"
"        \"length\": 5\n"
"    }, \n"
"    \"widget_ram_label\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"return 'Ram:'\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 4\n"
"    }, \n"
"    \"widget_ram_total\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"return meminfo.Meminfo('MemTotal')/1024\", \n"
"        \"type\": \"text\", \n"
"        \"precision\": 0,\n"
"        \"update\": 500, \n"
"        \"length\": 5\n"
"    }, \n"
"    \"widget_system_bar\": {\n"
"        \"expression\": \"return procstat.Cpu('system', 500)\", \n"
"        \"style\": \"H\", \n"
"        \"type\": \"bar\", \n"
"        \"width\": 10\n"
"    }, \n"
"    \"widget_system_histogram\": {\n"
"        \"direction\": \"E\", \n"
"        \"expressionn\": \"return procstat.Cpu('system', 500)\", \n"
"        \"gap\": 1, \n"
"        \"type\": \"histogram\", \n"
"        \"width\": 10\n"
"    }, \n"
"    \"widget_system_label\": {\n"
"        \"align\": \"R\", \n"
"        \"prefix\": \"return 'System: '\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 10\n"
"    }, \n"
"    \"widget_wlan0\": {\n"
"        \"align\": \"L\", \n"
"        \"expression\": \"return netdev.Fast('wlan0', 'Tx_bytes', 100) /1024\", \n"
"        \"precision\": 0, \n"
"        \"type\": \"text\", \n"
"        \"update\": 500, \n"
"        \"length\": 3\n"
"    }, \n"
"    \"widget_wlan0_bar\": {\n"
"        \"expression\":  \"return netdev.Fast('wlan0', 'Rx_bytes', 500) / 1024\", \n"
"        \"expression2\": \"return netdev.Fast('wlan0', 'Tx_bytes', 500) / 1024\", \n"
"        //\"style\": \"H\", \n"
"        \"type\": \"bar\", \n"
"        \"update\": 500, \n"
"        \"width\": 10\n"
"    }, \n"
"    \"widget_wlan0_histogram\": {\n"
"        \"direction\": \"E\", \n"
"        \"expression\": \n"
"\"return (netdev.Fast('wlan0', 'Rx_bytes', 500) + netdev.Fast('wlan0', 'Tx_bytes', 500)) /1024\", \n"
"        \"gap\": 1, \n"
"        \"type\": \"histogram\", \n"
"        \"update\": 500, \n"
"        \"width\": 10\n"
"    }, \n"
"    \"widget_wlan0_label\": {\n"
"        \"expression\": \"return 'wlan0:'\", \n"
"        \"type\": \"text\", \n"
"        \"length\": 6\n"
"    }, \n"
"    \"widget_wlan0_short_bar\": {\n"
"        \"expression\": \"return (netdev.Fast('wlan0', 'Rx_bytes', 500) + netdev.Fast('wlan0', 'Tx_bytes', 500)) /1024\", \n"
"        \"length\": 7, \n"
"        \"style\": \"N\", \n"
"        \"type\": \"bar\", \n"
"        \"update\": 500\n"
"    },\n"
"    \"widget_netstat_script\": {\n"
"        \"file\": \"netstat_script.js\",\n"
"        \"type\": \"script\"\n"
"    }\n"
"}\n\n";
