import subprocess
import sys

visualCflags, visualCflagse = subprocess.Popen(["pkg-config", "--cflags", "libvisual-0.5"],
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

pulseCflags, pulseCflagse = subprocess.Popen(Split("pkg-config --cflags libpulse libpulse-simple"),
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

output = visualCflags + " " + pulseCflags

env = Environment(CCFLAGS = Split("-g -Wall " + output))

visualLdflags, visualLdflagse = subprocess.Popen(["pkg-config", "--libs", "libvisual-0.5"],
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

pulseLdflags, pulseLdflagse = subprocess.Popen(Split("pkg-config --libs libpulse libpulse-simple"),
    stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()

output = visualLdflags + " " + pulseLdflags

libs = env.ParseFlags(Split(output));
env.MergeFlags(libs)

plugin = env.SharedLibrary(["input_pulseaudio.c"]);

env.Install("/usr/lib/libvisual-0.5/input/", plugin);
env.Alias('install', '/usr/lib/libvisual-0.5/input')


