FIND_PATH(OPENGL_ES1_INCLUDE_DIR GLES/gl.h
  DOC "The OpenGL ES1 include directory")
FIND_LIBRARY(OPENGL_ES1_LIBRARY NAMES GLESv1_CM
  DOC "The OpenGL ES1 library")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES1 DEFAULT_MSG
  OPENGL_ES1_LIBRARY OPENGL_ES1_INCLUDE_DIR)

IF(OpenGLES1_FOUND)
  IF(NOT TARGET OpenGLES1::GL)
    ADD_LIBRARY(OpenGLES1::GL UNKNOWN IMPORTED)
    SET_TARGET_PROPERTIES(OpenGLES1::GL PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${OPENGL_ES1_INCLUDE_DIR}"
      IMPORTED_LINK_INTERFACE_LANGUAGES "C"
      IMPORTED_LOCATION "${OPENGL_ES1_LIBRARY}")
  ENDIF()
ENDIF()

MARK_AS_ADVANCED(
  OPENGL_ES1_INCLUDE_DIR
  OPENGL_ES1_LIBRARY
)
