FIND_PATH(T1LIB_INCLUDE_DIR NAMES t1lib.h
  DOC "The t1lib include directory")
FIND_LIBRARY(T1LIB_LIBRARY NAMES t1
  DOC "The t1lib library")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T1lib DEFAULT_MSG
  T1LIB_LIBRARY T1LIB_INCLUDE_DIR)

IF(T1lib_FOUND)
  SET(T1LIB_INCLUDE_DIRS ${T1LIB_INCLUDE_DIR})
  SET(T1LIB_LIBRARIES ${T1LIB_LIBRARY})

  IF(NOT TARGET T1lib::T1lib)
    ADD_LIBRARY(T1lib::T1lib UNKNOWN IMPORTED)
    SET_TARGET_PROPERTIES(T1lib::T1lib PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${T1LIB_INCLUDE_DIR}"
      IMPORTED_LINK_INTERFACE_LANGUAGES "C"
      IMPORTED_LOCATION "${T1LIB_LIBRARY}")
  ENDIF()
ENDIF()

MARK_AS_ADVANCED(
  T1LIB_INCLUDE_DIR
  T1LIB_LIBRARY
)
