FIND_PATH(T1LIB_INCLUDE_DIR t1lib.h)
FIND_LIBRARY(T1LIB_LIBRARY NAMES t1)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T1lib DEFAULT_MSG T1LIB_LIBRARY T1LIB_INCLUDE_DIR)

MARK_AS_ADVANCED(
  T1LIB_INCLUDE_DIR
  T1LIB_LIBRARY
)
