FIND_PATH(OPENGL_ES1_INCLUDE_DIR GLES/gl.h)
FIND_LIBRARY(OPENGL_ES1_LIBRARY NAMES GLESv1_CM)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES1 DEFAULT_MSG OPENGL_ES1_LIBRARY OPENGL_ES1_INCLUDE_DIR)

MARK_AS_ADVANCED(
  OPENGL_ES1_INCLUDE_DIR
  OPENGL_ES1_LIBRARY
)
