MACRO(PKG_GET_MODULE_VAR PKG_NAME VAR_NAME OUTPUT_VAR)
  EXECUTE_PROCESS(
    COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=${VAR_NAME} ${PKG_NAME}
    OUTPUT_VARIABLE ${OUTPUT_VAR}
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
ENDMACRO()
