PKG_CHECK_MODULES(ORC orc-0.4>=0.4.6 IMPORTED_TARGET)

PKG_GET_VARIABLE(ORC_COMPILER_EXECUTABLE orc-0.4 orcc)
MARK_AS_ADVANCED(ORC_COMPILER_EXECUTABLE)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ORC DEFAULT_MSG ORC_COMPILER_EXECUTABLE ORC_FOUND)
