PKG_CHECK_MODULES(ORC orc-0.4>=0.4.6 IMPORTED_TARGET)

FIND_PROGRAM(ORC_COMPILER_EXECUTABLE orcc)
MARK_AS_ADVANCED(ORC_COMPILER_EXECUTABLE)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ORC DEFAULT_MSG ORC_COMPILER_EXECUTABLE ORC_FOUND)
