INCLUDE(CMakeParseArguments)

FUNCTION(LV_BUILD_TEST TEST_NAME)
  SET(OPTION_ARGS "")
  SET(SINGLE_ARGS "")
  SET(MULTI_ARGS  "ARGS" "SOURCES" "COMPILE_DEFS" "COMPILE_FLAGS" "INCLUDE_DIRS" "LINK_DIRS" "LINK_LIBS")
  CMAKE_PARSE_ARGUMENTS(PARSED_ARGS "${OPTION_FLAGS}" "${SINGLE_ARGS}" "${MULTI_ARGS}" ${ARGN})

  IF(NOT PARSED_ARGS_SOURCES)
    MESSAGE(FATAL_ERROR "Cannot build unit test '${TEST_NAME}', no source files specified.")
  ENDIF()

  ADD_EXECUTABLE(${TEST_NAME} ${PARSED_ARGS_SOURCES})

  IF(${PARSED_ARGS_COMPILE_DEFS})
    ADD_DEFINITIONS(${PARSED_ARGS_COMPILE_DEFS})
  ENDIF()

  INCLUDE_DIRECTORIES(
    ${PROJECT_SOURCE_DIR}
    ${PROJECT_BINARY_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_BINARY_DIR}
    ${PARSED_ARGS_INCLUDE_DIRS}
  )

  IF(${PARSED_ARGS_LINK_DIRS})
    LINK_DIRECTORIES(${PARSED_ARGS_LINK_DIRS})
  ENDIF()

  TARGET_LINK_LIBRARIES(${TEST_NAME}
    libvisual
    ${CMAKE_THREAD_LIBS_INIT}
    ${PARSED_ARGS_LINK_LIBS}
  )

  ADD_TEST(${TEST_NAME}
    ${CMAKE_COMMAND} -E chdir ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}/${TEST_NAME} ${PARSE_ARGS_ARGS}
  )
ENDFUNCTION()
