#ifndef _OINK_CONFIG_DEFINES_H
#define _OINK_CONFIG_DEFINES_H

#define CONFIG_BLURMODES	2
#define CONFIG_MUSICMOODS	3
#define CONFIG_SCOPEMODES	8
#define CONFIG_BACKGROUNDMODES	6

#endif /* _OINK_CONFIG_DEFINES_H */
