#!/bin/bash

gcc -o libvis-scale libvis-scale.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-sub libvis-sub.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-rect-blit libvis-rect-blit.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-composite libvis-composite.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-rect-blit-scale libvis-rect-blit-scale.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-color-fill libvis-color-fill.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-meng libvis-meng.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-blit libvis-blit.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-depth libvis-depth.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-blit2 libvis-blit2.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-scale-bench libvis-scale-bench.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-bmp libvis-bmp.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-vnc libvis-vnc.c `libvncserver-config --libs --cflags` -ggdb -lvisual
gcc -o windowtje windowtje.c `sdl-config --libs --cflags` -ggdb

