#!/bin/bash

gcc -o libvis-scale libvis-scale.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-meng libvis-meng.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-blit libvis-blit.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-blit2 libvis-blit2.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o libvis-scale-bench libvis-scale-bench.c `sdl-config --libs --cflags` -ggdb -lvisual
gcc -o windowtje windowtje.c `sdl-config --libs --cflags` -ggdb

