name: Enforce that .po/.pot files are in sync with the code

on:
  pull_request:
  push:
  schedule:
    - cron: '0 3 * * 5'  # Every Friday at 3am

env:
  LV_INSTALL_PREFIX: /home/runner/.local/

jobs:
  translations:
    name: Enforce that .po/.pot files are in sync with the code
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |-
          sudo apt-get update
          # Note: This additional step's sole purpuse is to workaround symptom:
          #       > The following packages have unmet dependencies:
          #       >  libunwind-14-dev : Breaks: libunwind-dev but 1.3.2-2build2
          #       >                             is to be installed
          sudo apt-get install --yes --no-install-recommends libunwind-dev
          sudo apt-get install --yes --no-install-recommends \
            autopoint \
            bison \
            doxygen \
            flex \
            gettext \
            graphviz \
            libgstreamer1.0-dev \
            libgtk-3-dev \
            libjack-dev \
            libluajit-5.1-dev \
            liborc-0.4-dev \
            libpng-dev \
            libasound2-dev \
            libsdl1.2-dev \
            libgl1-mesa-dev \
            moreutils \
            pkg-config

      - name: Checkout Git branch
        uses: actions/checkout@v3

      - name: '[LV] Run autoreconf'
        run: |-
          for i in libvisual libvisual-plugins ; do
            pushd ${i}
              autoreconf --install --verbose --force
            popd
          done

      - name: '[LV] Run "./configure" (from Git)'
        run: |-
          cd libvisual
          ./configure \
            --prefix ${LV_INSTALL_PREFIX} \

      - name: '[LV] Run "make"'
        run: |-
          make -C libvisual -j2 VERBOSE=1

      - name: '[LV] Run "make install"'
        run: |-
          make -C libvisual install
          find ${LV_INSTALL_PREFIX} | sort

      - name: '[Plugins] Run "./configure" (from Git)'
        run: |-
          cd libvisual-plugins
          PKG_CONFIG_PATH=${LV_INSTALL_PREFIX}/lib/pkgconfig/ \
            ./configure

      - name: 'Enforce that .po/.pot files are in sync with the code'
        run: |-
          .github/workflows/translations.sh
          git diff --exit-code  # i.e. fail CI with details if non-empty
