#!/bin/sh

####
# small script to create a snapshot of every installed actor
# using lv-tool and imagemagick - 2013 - D.Hiepler


# path where actor plugins are
ACTORPATH="/usr/local/lib/libvisual-0.5/actor"
# dimensions of snapshot
WIDTH=320
HEIGHT=200
# snapshot the n-th rendered frame
FRAME=100


# walk through all actors
for ACTORFILE in ${ACTORPATH}/libactor_* ; do
    ACTOR=${ACTORFILE##*/libactor_}
    ACTOR=${ACTOR%%.*}

    # calculate amount of bytes to skip
    SKIP=$[WIDTH*HEIGHT*3*FRAME]

    # render & snapshot
    echo "Snapshotting ${ACTOR}"
    lv-tool -F$[FRAME+1] -d stdout -D${WIDTH}x${HEIGHT} -c24 -a ${ACTOR} 2>/dev/null | convert -size ${WIDTH}x${HEIGHT}+${SKIP} -depth 8 rgb:- -separate -swap 0,2 -combine ${ACTOR}.png
done
